name: twit_analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit
      - fastapi
      - uvicorn
      - pydantic
      - requests
      - pandas
      - "numpy<2.0"
      - scikit-learn
      - bertopic==0.17.3
      - sentence-transformers
      - joblib
      - xgboost
      - torch
      - plotly
      - matplotlib
      - seaborn
      - altair
